version: '3'
services:
  stream-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      STREAMING_URL: "https://stream.upfluence.co/stream"
      PORT: "8089"
